groups:
- name: example
  rules:

  - alert: service_down
    expr: up == 0
    for: 0s
    labels:
      severity: page
    annotations:
      summary: "Instance {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 30 seconds."

  - alert: HostSystemdServiceCrashed
    expr: (node_systemd_unit_state{state="inactive", name='apache2.service'} == 1)
    for: 0m
    labels:
      severity: warning
    annotations:
      summary: Host systemd service crashed (instance {{ $labels.instance }})
      description: "systemd service crashed\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"