global:
    http_config:
        basic_auth:
            username: "admin"
            password: "admin"
route:
    group_interval: 10s
    repeat_interval: 1m
    receiver: 'pager'   

receivers:
    - name: 'pager'
      webhook_configs:
      - url: 'http://localhost:777' # replace with your PagerTree webhook url