---
- name: Pull Kibana Docker image
  ansible.builtin.command: podman pull docker.elastic.co/kibana/kibana:{{ kibana_version }}
  become: true

- name: Create Kibana directory
  file:
    path: /etc/kibana
    state: directory
  become: true

- name: Copy Kibana config file
  copy:
    src: kibana.yml
    dest: /etc/kibana/kibana.yml
  become: true

- name: Start Kibana Docker container
  ansible.builtin.command: podman run -d --name kibana --network host -v /etc/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro docker.elastic.co/kibana/kibana:{{ kibana_version }}
  become: true