
- block:
  # - name: "delete filebeat"
  #   apt:
  #     name: "filebeat"
  #     state: absent

  # - name: "adding a source line to /etc/apt/sources.list.d/elastic-7.x.list" 
  #   lineinfile:
  #     path: "/etc/apt/sources.list.d/elastic-7.x.list"
  #     line: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"
  #     insertbefore: "BOF"
  #     create: "yes"

  # - name: "Install the package apt-transport-https"
  #   apt:
  #     name: "apt-transport-https"
  #     allow_unauthenticated: "yes"
  #     install_recommends: "yes"

  # - name: "Singing key" 
  #   shell: 'wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | apt-key add -'

  # - name: "apt-get update"
  #   apt:
  #     update_cache: "yes" 
  #   ignore_errors: "yes"

  # - name: "Install the package filebeat"
  #   apt:
  #     name: "filebeat={{ filebeat_version }}"
  #     allow_unauthenticated: "yes"
  #     install_recommends: "yes"
  #   ignore_errors: "yes"

  # - name: "copy file fields.yml to /etc/filebeat/" 
  #   copy:
  #     src: "fields.yml"
  #     dest: "/etc/filebeat/fields.yml" 
  #     owner: "root" 
  #     group: "root" 
  #     mode: 0640 
  - name: Create a directory /etc/filebeat
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      mode: '0755'
    loop:
      - /etc/filebeat
      - /etc/filebeat/modules.d

  - name: "copy file filebeat.yml to /etc/filebeat/" 
    template:
      src: "filebeat/filebeat.minimal.yml.j2"
      dest: "/etc/filebeat/filebeat.yml" 
      mode: 0640 
    tags:
      - config

  # - name: copy file pg_fields.yml to /etc/filebeat/ 
  #   copy:
  #     src: "filebeat/pg_fields.yml"
  #     dest: "/etc/filebeat/pg_fields.yml" 
  #     mode: 0640 
  #   tags:
  #     - config

  - name: configure postgresql module
    block:
    # - name: "rm file postgresql.yml.disabled from /etc/filebeat/modules.d/" 
    #   file:
    #     path: "/etc/filebeat/modules.d/postgresql.yml.disabled"
    #     state: absent

    - name: "copy file postgresql.yml to /etc/filebeat/modules.d/" 
      template:
        src: "filebeat/postgresql.yml.j2"
        dest: "/etc/filebeat/modules.d/postgresql.yml"
        mode: 0640 
    when: filebeat_postgresql

  - name: configure system module
    block:
  #   - name: "rm file system.yml.disabled from /etc/filebeat/modules.d/" 
  #     file:
  #       path: "/etc/filebeat/modules.d/system.yml.disabled"
  #       state: absent

    - name: "copy file system.yml to /etc/filebeat/modules.d/" 
      template:
        src: "filebeat/system.yml.j2"
        dest: "/etc/filebeat/modules.d/system.yml"
        mode: 0640 
    when: filebeat_system

  - name: configure tomcat module
    block:
  #   - name: "rm file tomcat.yml.disabled from /etc/filebeat/modules.d/" 
  #     file:
  #       path: "/etc/filebeat/modules.d/tomcat.yml.disabled"
  #       state: absent

    - name: "copy file tomcat.yml to /etc/filebeat/modules.d/" 
      template:
        src: "filebeat/tomcat.yml.j2"
        dest: "/etc/filebeat/modules.d/tomcat.yml"
        mode: 0640 
    when: filebeat_tomcat

  - name: configure zookeeper module
    block:
  #   - name: "rm file zookeeper.yml.disabled from /etc/filebeat/modules.d/" 
  #     file:
  #       path: "/etc/filebeat/modules.d/zookeeper.yml.disabled"
  #       state: absent

    - name: "copy file zookeeper.yml to /etc/filebeat/modules.d/" 
      template:
        src: "filebeat/zookeeper.yml.j2"
        dest: "/etc/filebeat/modules.d/zookeeper.yml"
        mode: 0640 
    when: filebeat_zookeeper

  # - name: "Configure Filebeat to start automatically during boot" 
  #   shell: 'update-rc.d filebeat defaults 95 10'

  # - name: "restart service filebeat"
  #   systemd:
  #     name: "filebeat"
  #     daemon_reexec: yes 
  #     enabled: yes
  #     state: restarted 
  #   tags:
  #     - config

  # - name: Stop filebeat container
  #   ansible.builtin.command: podman rm -f filebeat
  #   ignore_errors: true

  # - name: Start filebeat container
  #   ansible.builtin.command: podman run -d -ti \
  #     --privileged \
  #     -u root \
  #     --hostname {{ ansible_hostname }} \
  #     --name=filebeat \
  #     --network {{ elk_network }} \ 
  #     --volume="/etc/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro" \
  #     --volume="/etc/filebeat/modules.d:/usr/share/filebeat/modules.d:ro" \
  #     --volume="/var/log:/var/log:ro" \
  #     {{ filebeat_image }}

  - name: Configure filebeat systemd service
    template:
      src: filebeat/filebeat.service.j2
      dest: "/usr/lib/systemd/system/filebeat.service"
    notify: Just force systemd to reread configs

  - name: Restart filebeat
    ansible.builtin.systemd:
      name: "filebeat.service"
      state: restarted
    become: true

  when: filebeat