---
- include: prepare.yml
  tags: prepare
- include: configure_cluster.yml
  tags: configure_cluster
- include: set_password.yml
  tags:
    - password
- include: enroll_kibana.yml
  tags:
    - kibana
- include: filebeat_install.yml
  tags: 
    - filebeat
- include: elasticsearch_delete.yml
  when: elastic_flush or flush_all
  tags: flush