- name: Set Elasticsearch password
  ansible.builtin.shell: |
    podman exec -ti elasticsearch-{{ elasticsearch_cluster_name }} /bin/bash -c 'yes {{ elasticsearch_password }} | /usr/share/elasticsearch/bin/elasticsearch-reset-password -b -u {{ elasticsearch_user }} -i' 
    podman exec -ti elasticsearch-{{ elasticsearch_cluster_name }} /bin/bash -c 'yes {{ kibana_password }} | /usr/share/elasticsearch/bin/elasticsearch-reset-password -b -u {{ kibana_user }} -i'
  # args:
  #   chdir: "{{ elasticsearch_install_dir }}/elasticsearch-{{ elasticsearch_version }}"
  register: password_output
  become: true
  # no_log: true

# - name: Set Elasticsearch 'elastic' user password fact
#   set_fact:
#     elasticsearch_password: "{{ password_output.stdout_lines | select('search', '^PASSWORD elastic = ') | map('regex_replace', '^PASSWORD elastic = ', '') | list | first }}"
#   become: true

# - name: Display generated Elasticsearch passwords
#   debug:
#     var: elasticsearch_password