- name: Set Elasticsearch password
  shell: |
    bin/elasticsearch-setup-passwords auto --batch
  args:
    chdir: "{{ elasticsearch_install_dir }}/elasticsearch-{{ elasticsearch_version }}"
  register: password_output
  become: true

- name: Set Elasticsearch 'elastic' user password fact
  set_fact:
    elasticsearch_password: "{{ password_output.stdout_lines | select('search', '^PASSWORD elastic = ') | map('regex_replace', '^PASSWORD elastic = ', '') | list | first }}"
  become: true

- name: Display generated Elasticsearch passwords
  debug:
    var: elasticsearch_password